### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by Rexbalaeniceps** [tushar117/Transformer-Models-for-Text-Coherence-Assessment#1]
Hi~ Thank you for your code. I got the following problem when run `python download_data.py`. Could you help me ~ ~ ~
```
Removing the existing directory...
creating processed data directory
Downloading Processed Dataset...
Traceback (most recent call last):
  File "download_data.py", line 61, in <module>
    with zipfile.ZipFile(file_store_path, 'r') as zfile:
  File "/usr/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by tushar117** [comment]
Hi
Thanks for notifying the issue. With the following steps, you mitigate the above issue.
You can manually download the dataset zip from [here](https://drive.google.com/file/d/11G8SC5ussSsGC-k7CeVrdsL-Xks8Aj4Q). Then create a directory `processed_data` within the project folder and unzip the downloaded content to this folder. 

please let me know if this works for you or not.

**Comment by Rexbalaeniceps** [comment]
Thanks very much ~ It does work.
